### ISSUE TITLE
Jekyll-autoprefixer and Compass

### ISSUE THREAD

**Issue by sackwort** [vwochnik/jekyll-autoprefixer#1]
Thank you for making your autoprefixer available.

I'm using Compass in my Jekyll project because it enables me to quite easily use SASS source maps. However, when I install and use jekyll-autoprefixer I am no longer able to see the source map reference in my Firefox's inspector, even though my main style.css file contains all of the relevant scss line comments.

I realise that you may not use Compass, but I just wondered if you could tell me why this happens, and if there might be a way around it?

**Comment by vwochnik** [comment]
Well, what this plugin does is it watches for css files being written by `jekyll` and subsequently `compass` and then simply reads them and pipes them back through `autoprefixer`. So, of course, your source maps are going to be invalid because this plugin does not actively write new source maps.

**Comment by sackwort** [comment]
OK. Thanks very much for your reply.
